### ISSUE TITLE
java.lang.ClassCastException: java.lang.Boolean cannot be cast to org.json.simple.JSONArray

### ISSUE THREAD

**Issue by timbru31** [timbru31/updater#2]
[00:05:27] [Thread-39/INFO]: https://api.curseforge.com/servermods/files?projectIds=35890[m
[00:05:27] [Thread-39/WARN]: Exception in thread "Thread-39"
[00:05:27] [Thread-39/WARN]: java.lang.ClassCastException: java.lang.Boolean cannot be cast to org.json.simple.JSONArray
[00:05:27] [Thread-39/WARN]:    at de.dustplanet.util.Updater.read(Updater.java:692)
[00:05:27] [Thread-39/WARN]:    at de.dustplanet.util.Updater.runUpdater(Updater.java:765)
[00:05:27] [Thread-39/WARN]:    at de.dustplanet.util.Updater.access$100(Updater.java:38)
[00:05:27] [Thread-39/WARN]:    at de.dustplanet.util.Updater$UpdateRunnable.run(Updater.java:760)
[00:05:27] [Thread-39/WARN]:    at java.lang.Thread.run(Unknown Source)
[00:05:27] [Server thread/INFO]: [SilkSpawners] Result from AutoUpdater is: SUCCESS

**Comment by timbru31** [comment]
Caused by a "PluginInterceptor" used to enable cracked plugins. Nevertheless on exception Updater should return an error and catch this.

**Comment by timbru31** [comment]
Refactoring to Gson makes this issue obsolete.
